# The cnfig for travis CI
sudo: required

language: python

python:
    - "2.7"
env:  
    global:
        - DOCKER_VERSION=1.12.2-0~trusty

services:  
    - docker

before_install:  
    # list docker-engine versions
    - sudo apt-cache madison docker-engine
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce

    # reinstall docker-compose at specific version
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > docker-compose
    - sudo chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - sudo sysctl -w vm.max_map_count=262144

script:  
    - sudo service docker restart
    - sudo docker-compose -f docker-compose-test.yml up
    - sudo docker-compose -f docker-compose-test-rerun.yml up
