#Run docker container in the background
#docker-compose up -d
version: '2'
services:
  aws-elk-billing:
    image: airdata/aws-billing-kibana
    build: .
    environment:
    - DEBIAN_FRONTEND=noninteractive
    - TERM=xterm
    - ENV=prod
    volumes:
    - .:/aws-elk-billing
    depends_on:
    - kibana
    - logstash
    - elasticsearch
    links:
    - kibana:kibana
    - logstash:logstash
    - elasticsearch:elasticsearch
    env_file:
    - prod.env.example
    command: bash -c "python -u /aws-elk-billing/orchestrate.py"