version: 2.1
jobs:
  build_jenkins:
    machine: true
    working_directory: ~/aws-billing-kibana-in-docker

    steps:
      - checkout
      - attach_workspace:
          at: ~/aws-billing-kibana-in-docker
      - run:
          name: Load archived Docker image
          command: |
            docker-compose -f docker-compose.yml build aws-elk-billing
      - deploy:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
            docker-compose -f docker-compose.yml push aws-elk-billing
workflows:
  version: 2
  default:
    jobs:
      - build_jenkins
